import Head from 'next/head'
import Image from 'next/image'
import SectionBanner from '../components/home/SectionBanner'
import SectionTwo from '../components/home/SectionTwo'
import SectionThree from '../components/home/SectionThree'
import SectionFour from '../components/home/SectionFour'
import SectionFive from '../components/home/SectionFive'
import SectionSix from '../components/home/SectionSix'
import SectionSeven from '../components/home/SectionSeven'

export default function Home() {
  return (
    <div className="bg-black">
      <Head>
        <title>Cosmohub</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        
        <SectionBanner />
        <SectionTwo />
        <SectionThree />
        <SectionFour />
        <SectionFive />
        <SectionSix />
        <SectionSeven />
      </main>

    </div>
  )
}
